INSERT INTO bossfight (bossid,playerid,fightresult) VALUES (2,2,'Игрок проиграл');
INSERT INTO bossfight (bossid,playerid,fightresult) VALUES (2,2,'Игрок победил');
INSERT INTO bossfight (bossid,playerid,fightresult) VALUES (2,1,'Игрок победил');
INSERT INTO bossfight (bossid,playerid,fightresult) VALUES (2,1,'Игрок победил');
INSERT INTO bossfight (bossid,playerid,fightresult) VALUES (2,2,'Игрок проиграл');
INSERT INTO Fight (exmobId,playerid,fightresult) VALUES (2,2,'Игрок проиграл');
INSERT INTO Fight (exmobId,playerid,fightresult) VALUES (2,1,'Игрок победил');
INSERT INTO Fight (exmobId,playerid,fightresult) VALUES (2,1,'Игрок победил');
INSERT INTO Fight (exmobId,playerid,fightresult) VALUES (5,1,'Игрок победил');
INSERT INTO Fight (exmobId,playerid,fightresult) VALUES (3,1,'Игрок победил');
INSERT INTO Fight (exmobId,playerid,fightresult) VALUES (4,1,'Игрок победил');
INSERT INTO Fight (exmobId,playerid,fightresult) VALUES (4,1,'Игрок победил');
INSERT INTO Fight (exmobId,playerid,fightresult) VALUES (17,3,'Игрок победил');
SELECT * FROM showPlayerInventory(3);
SELECT * FROM showPlayerSkills(4);
SELECT * FROM howtogetitem('Легендарная удочка');