DROP TYPE IF EXISTS status CASCADE;
DROP TYPE IF EXISTS gender CASCADE;
DROP TYPE IF EXISTS floor_status CASCADE;
DROP TYPE IF EXISTS method_to_get_item CASCADE;
DROP TYPE IF EXISTS method_to_get_skill CASCADE;
DROP TYPE IF EXISTS fight_result CASCADE;
DROP TABLE IF EXISTS ExistMobs CASCADE;
DROP TABLE IF EXISTS Player CASCADE;
DROP TABLE IF EXISTS Inventory CASCADE;
DROP TABLE IF EXISTS Item CASCADE;
DROP TABLE IF EXISTS Inventory_Item CASCADE;
DROP TABLE IF EXISTS Armor CASCADE;
DROP TABLE IF EXISTS Equipment CASCADE;
DROP TABLE IF EXISTS Weapons CASCADE;
DROP TABLE IF EXISTS Skill CASCADE;
DROP TABLE IF EXISTS Skill_Player CASCADE;
DROP TABLE IF EXISTS Floor CASCADE;
DROP TABLE IF EXISTS Boss CASCADE;
DROP TABLE IF EXISTS Mob CASCADE;
DROP TABLE IF EXISTS Location CASCADE;
DROP TABLE IF EXISTS fight CASCADE;
DROP TABLE IF EXISTS bossfight CASCADE;
DROP FUNCTION IF EXISTS showplayerinventory

DROP FUNCTION IF EXISTS showplayerskills